#配置服务器信息
server:
  port: 9527


#数据库信息配置
spring:
  application:
    name: microservicecloud-zuul-gateway #应用名称

#客户端注册进eureka服务列表 
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7001.com:7001/eureka
  instance: 
      instance-id: gateway-9527.com #服务实例名称修改
      prefer-ip-address: true #显示ip
      
zuul: 
  routes:  
    mydept.serviceId: microservicecloud-provider-dept
    mydept.path: /mydept/**
  #多个用"*" ignored-services: "*" 忽略掉
  ignored-services: microservicecloud-provider-dept
  #公共前缀
  prefix: /hy
info:
  app.name: microservicecloud-Test
  company.name: www.hy.com
  build.artifactId: microservicecloud-study-zuul-gateway-9527
  build.version: 0.0.1-SNAPSHOT

    