server:
  port: 3344
spring:
  application:
    name: springcloud-hy-config
  cloud:
    config:
      server:
        git:
          # uri: git@github.com:gongxings/springcloud-study-config.git
          uri: https://github.com/specialhy/springclud-bili-config.git

